config/routes.rb
Rails.application.routes.draw do

	root to: 'store#index'

  get 'carts/create/:product_id', to: 'carts#create', as: "add_product_to_cart"

	devise_for :users
	resources :users

	get '/products/:id', to: 'products#show', as: 'product'

	get '/carts/cart_count', to: 'carts#cart_count'

	scope 'carts' do
	  get 'checkouts/(:token)', :to => 'checkouts#show'
	  resources :checkouts, only: :create
	end

	get '/carts/:token', to: 'carts#show'

	resources :carts, only: [:index, :create]


	resources :cart_items, only: :create
	resources :collections

	get 'orders/confirmation/(:confirmation)', :to => 'orders#confirmation', as: 'confirmation'

	namespace :admin do
		root to: 'dashboards#index'
	  resources :dashboards
	  resources :products, except: :show
	  resources :orders, only: ['index']
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/billing_address.rb
class BillingAddress < ApplicationRecord
	belongs_to :order
end

app/models/cart.rb
class Cart < ApplicationRecord
	has_many :cart_items
	has_many :products, through: :cart_items

	after_destroy :destroy_cart_items

	def self.total cart
		total = 0
		cart.cart_items.each { |i| puts total += i.product.price * i.quantity }
		total
	end

	private

	def destroy_cart_items
		self.cart_items.each do |item|
	    item.destroy
		end
	end

end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	belongs_to :product
	belongs_to :cart
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :product_categories
	has_many :products, through: :product_categories
end

app/models/collection.rb
class Collection < ApplicationRecord
	has_many :product_collections
	has_many :products, through: :product_collections
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :user

	has_many :order_items
	has_one :shipping_address
	has_one :billing_address

	scope :open, -> { where(closed: false) }

	def self.generate_confirmation
		SecureRandom.hex(5)
	end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
	belongs_to :order
	belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :orders
	has_many :users, through: :orders, :source => :order

	has_many :product_collections
	has_many :collections, through: :product_collections

	has_many :product_categories
	has_many :categories, through: :product_categories

	has_many :order_items
	has_many :product_images
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
	belongs_to :product
	belongs_to :category
end

app/models/product_collection.rb
class ProductCollection < ApplicationRecord
	belongs_to :product
	belongs_to :collection
end

app/models/product_image.rb
class ProductImage < ApplicationRecord
	scope :thumbnail, -> { joins(:product).where( thumbnail: true ).first }

	belongs_to :product
end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
	belongs_to :order
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :orders
  has_many :products, through: :orders, source: :order
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/checkouts_helper.rb
module CheckoutsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Store Admin</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %> 
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Store</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://js.stripe.com/v2/', 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Cormorant+Garamond:400,600|Open+Sans:400,700" rel="stylesheet">


  </head>

  <body>
    <%= render partial: "partials/header", locals: {hero:true} %>
    <%= yield %> 
    <%= render partial: "partials/footer" %> 
  </body>
</html>

app/views/layouts/product.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Store</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "partials/header", locals: {hero:false} %>
    <%= yield %> 
    <!-- <%= render partial: "partials/footer" %> -->
  </body>
</html>

app/views/partials/_carousel.html.erb
<% if images.any? %>
      
  <div id="carousel1" class="carousel slide">
    <ol class="carousel-indicators">
      <% images.each_with_index do |image, index| %>
        <% if (index == 0) %>
          <li data-target="#carousel1" data-slide-to="<%= index %>" class="active"></li>
        <% else %>
          <li data-target="#carousel1" data-slide-to="<%= index %>"></li>
        <% end %>
      <% end %>
    </ol>
    <div class="carousel-inner" role="listbox">
      <% images.each_with_index do |image, index| %>
        <div class="carousel-item <%= index == 0 ? 'active' : '' %>">
          <%= image_tag("#{path}/#{image.name}", class: "d-block img-fluid", alt: "#{image.name}") %>
        </div>
      <% end %>
    </div>
    <a class="carousel-control-prev" href="#carousel1" role="button" data-slide="prev">
      <!-- <span class="carousel-control-prev-icon" aria-hidden="true"></span> -->
      <span class="controls"><</span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carousel1" role="button" data-slide="next">
      <!-- <span class="carousel-control-next-icon" aria-hidden="true"></span> -->
      <span class="controls">></span>
      <span class="sr-only">Next</span>
    </a>
  </div>

<% end %>

app/views/partials/_footer.html.erb
<section class="grid footer">

	<div class="copyright">
		<h3>GymBasis</h3>
		<p>&copy; 2017 GymBasis Inc.</p>
	</div>
	
	<div class="info">
		<div class="contact">
			<h3>Contact</h3>
			<p class="footer-item">885 N San Antonio Rd. <br> Los Altos, CA 94022</p>
			<p class="footer-item">650-935-5535</p>
			<p class="footer-item">sales@gymbasis.com</p>
		</div>

		<div class="support">
			<h3>Support</h3>
			<p class="footer-item">Privacy Policy</p>
			<p class="footer-item">Return Policy</p>
			<p class="footer-item">Pricing Errors</p>
		</div>

		<div class="about-us omega">
			<h3>About Us</h3>
			<p class="footer-item">Who we are</p>
			<p class="footer-item">Contacts</p>
		</div>
	</div>

	<div class="subscribe"></div>

</section>

app/views/partials/_header.html.erb
<section class="header">

  <div class="hero <%= hero ? 'with-image' : '' %>">
    <% if hero %> <div class="background-image"> <% end %>
      <div class="grid header-items"> 
        <% if hero %>
          <div class="inner-text">
            <h2 class="inner-item">New Arrival</h2>
            <p class="inner-item">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptates, itaque distinctio hic. Pariatur atque, cumque ex id quis maiores dolores. Saepe quae reiciendis blanditiis neque dolorem fugit vitae a quo?</p>
            <p><a class="btn inner-item" href="">Shop Now</a></p>
          </div> 
        <% end %>
          
        <div class="search">
          Search
        </div>
      
        <div class="logo tac">
          LOGO
        </div>

        <div class="cart tar">
          <%= react_component('CartComponent', count: 0) %>
        </div>

      </div> <!-- grid -->

      <%= render partial: "partials/nav" %>
    <%if hero %></div><% end %>
  </div>

</section>

app/views/partials/_modal.html.erb
<!-- Modal -->
<div class="modal grid fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Slider Images</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        
        <select multiple="multiple" class="image-picker">
          <% @all_product_images.each_with_index do |image_path, index| %>
            <option data-img-src="<%= "/assets/product_images/#{File.basename(image_path)}" %>" value="<%= File.basename(image_path) %>"></option>
          <% end %>
        </select>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

app/views/partials/_nav.html.erb
<section class="nav">

  <div class="grid-small">  
    <ul>
      <% header_collections.each_with_index do |col, i| %>
        <li class="nav-item <%= header_collections.size-1 == i ? 'omega' : '' %> ">
          <%= link_to col.display_name, collection_path(col.name) %>
        </li>
      <% end %>
    </ul>
  </div> <!-- grid -->

</section>

app/views/partials/_product.html.erb
<% click_edit = (action == "update" or action == "create") ? 'js-clickEdit' : '' %>
<section class="product-page grid <%= click_edit %>" data-action="<%= action %>" data-product-id="<%= id ||= '' %>">
	
	<div class="slider">
		<%= render partial: "partials/carousel", locals: {images: @images ||= [], path: "product_images"} %>
	</div>

	<div class="copy">
		<h1 class="name js-editor" data-edit="name">
			<%= @product.name || "Product Name" %>
		</h1>

		<div class="price cf">
			<span class="dollar">$</span>
			<p class="amount js-editor" data-edit="price">
				<%= @product.price || "0" %>
			</p>
			</div>

		<div class="add-cart cf">

			<div class="quantity">
				<%= react_component('QuantityBox') %>
			</div>
			<div class="add-cart-btn">
				<%= button_tag "Add to Cart", class:'btn wide js-add-cart' %>
			</div>

		</div>

	</div>

	<div class="description js-wysiwyg" data-edit="description">
		<%= @product.description? ? @product.description.html_safe : "Product Description" %>
	</div>

<% if user_signed_in? %> <!-- make admin check -->
	<% if action == "create" %>
		<button class="btn <%= "js-#{action}" %>">Create Product</button>
	<% elsif action == "update" %>
		<button class="btn <%= "js-#{action}" %>">Update Product</button>
	<% end %>

	<!-- Button trigger modal -->
	<button type="button" class="btn" data-toggle="modal" data-target="#myModal">
	  Launch demo modal
	</button>
<% end %>

<% if params[:action] != "show" %>
	<%= render partial: "partials/modal" %>
<% end %>

<div data-product="<%= @product.to_json %>" class="js-product"></div>
</section>